/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yellow;

import java.io.IOException;

import org.jline.reader.LineReader;
import org.jline.reader.LineReaderBuilder;
import org.jline.terminal.Terminal;
import org.jline.terminal.TerminalBuilder;

public class App {
	public String getGreeting() {
		return "Hello World!";
	}

	public static void main(String[] args) {
		try (Terminal terminal = TerminalBuilder.terminal()) {
			LineReader lineReader = LineReaderBuilder.builder() //
					.terminal(terminal) //
					.build();

			for (;;) {
				String line = lineReader.readLine("jline> ", null, "default value");

				terminal.writer().println(line);
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
